{
  # SSTable directory
  sstable-dir: "./data/sstable",
  # WAL directory
  wal-dir: "./data/wal",

  # The size of memtable in Bytes
  memtable-size: 1024,

  # The WAL sync time in milliseconds.
  # It would make disk writes efficient by grouping write requests.
  # Each write would keep waiting for at most this window time.
  sync-window-time: 200,

  # Bloom filter config
  bloom-filter:
  {
    hash-algo: "SHA-256",
    size: 10240,
    num-hashes: 4,
  }
}
